const String CREATE_CONTRATOS_TABLE_SCRIPT = ""
    "CREATE TABLE contratos("
    "id INTEGER PRIMARY KEY autoincrement,"
    "contrato INTEGER, "
    "nome TEXT, "
    "cpf_cnpj TEXT, "
    "localizacao TEXT,"
    "localidade INTEGER,"
    "localidade_nome TEXT, "
    "setor INTEGER, "
    "ciclo INTEGER,"
    "rota INTEGER,"
    "sequencia INTEGER,"
    "logradouro TEXT,"
    "numero INTEGER,"
    "bairro TEXT,"
    "complemento TEXT,"
    "cep TEXT,"
    "categoria TEXT,"
    "categoria_compacta TEXT,"
    "lista_categorias TEXT,"
    "sit_agua TEXT,"
    "sit_esgoto	TEXT,"
    "perc_agua INTEGER,"
    "perc_esgoto INTEGER,"
    "dt_leitura_ant DATE,"
    "leitura_ant INTEGER,"
    "media_consumo INTEGER,"
    "leitura_min INTEGER,"
    "leitura_max INTEGER,"

    "tarifa INTEGER,"
    "ciclo INTEGER,"

    ")";

const String CREATE_CATEGORIAS_TABLE_SCRIPT = ""
    "CREATE TABLE categorias("
    "id INTEGER PRIMARY KEY autoincrement,"
    "contrato_id INTEGER, "
    "categoria INTEGER, "
    ")";